-- V3: Atualização de conteúdo — descrições mais ricas para cursos, disciplinas e posts

-- -------------------------------------------------------
-- CURSOS — descrições mais completas
-- -------------------------------------------------------
UPDATE curso SET
  descricao = 'O curso de Análise e Desenvolvimento de Sistemas forma profissionais capacitados para desenvolver, implementar e manter sistemas de software de alto desempenho. Com uma grade curricular atualizada e metodologias ágeis, o egresso estará apto a atuar com linguagens modernas (Java, Python, JavaScript), bancos de dados relacionais e NoSQL, arquiteturas de microserviços e cloud computing. O curso alia teoria à prática intensa por meio de laboratórios, projetos interdisciplinares e parceria com empresas da região.',
  imagem_url = 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80'
WHERE codigo = 'TADS';

UPDATE curso SET
  descricao = 'O curso de Gestão Empresarial prepara líderes e empreendedores para os desafios do mercado contemporâneo. Os alunos desenvolvem competências em planejamento estratégico, gestão financeira, marketing digital, recursos humanos e empreendedorismo. Com um olhar voltado para a inovação e sustentabilidade, o egresso está habilitado a gerir departamentos, criar novos negócios e transformar organizações públicas e privadas.',
  imagem_url = 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80'
WHERE codigo = 'GE';

UPDATE curso SET
  descricao = 'O curso de Sistemas para Internet forma desenvolvedores full-stack com foco em web e mobile. Os alunos dominam as principais tecnologias do mercado: React, Vue, Node.js, APIs REST e GraphQL, além de práticas de UX/UI design, segurança de aplicações web e computação em nuvem. O curso tem forte ênfase em projetos práticos e integração com o ecossistema de startups e empresas de tecnologia.',
  imagem_url = 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80'
WHERE codigo = 'SI';

-- -------------------------------------------------------
-- DISCIPLINAS — ementas mais detalhadas
-- -------------------------------------------------------
UPDATE disciplina SET ementa = 'Introdução à lógica de programação e pensamento computacional. Algoritmos e fluxogramas. Variáveis, tipos de dados e operadores. Estruturas de controle: condicionais e laços. Sub-rotinas e funções. Introdução à linguagem Python e/ou Java. Vetores e matrizes. Resolução de problemas práticos com código.' WHERE codigo = 'ALG001';

UPDATE disciplina SET ementa = 'Fundamentos de banco de dados relacional. Modelo Entidade-Relacionamento (ER). Projeto conceitual, lógico e físico. Normalização e formas normais. SQL completo: DDL, DML, DQL. Funções de agregação, JOINs, subconsultas. Introdução ao PostgreSQL e MySQL. Boas práticas de modelagem.' WHERE codigo = 'BD001';

UPDATE disciplina SET ementa = 'Introdução à Engenharia de Software. Modelos de ciclo de vida: cascata, espiral e ágil. Scrum e Kanban na prática. Levantamento e gestão de requisitos. Modelagem UML: casos de uso, diagrama de classes, sequência e atividades. Qualidade de software e testes. Gestão de configuração e versionamento com Git.' WHERE codigo = 'ES001';

UPDATE disciplina SET ementa = 'Fundamentos da Programação Orientada a Objetos com Java. Classes, objetos, atributos e métodos. Encapsulamento, herança e polimorfismo. Interfaces e classes abstratas. Tratamento de exceções. Collections Framework. Generics e lambdas. Padrões de projeto (Design Patterns) introdutórios.' WHERE codigo = 'POO001';

UPDATE disciplina SET ementa = 'Estrutura de documentos HTML5 semântico. Estilização com CSS3: Flexbox e Grid Layout. Responsividade e mobile first. JavaScript moderno (ES6+): variáveis, funções, assincronismo, fetch API. Introdução ao React: componentes, props, estado e hooks. Ferramentas de build: Vite e Webpack.' WHERE codigo = 'WEB001';

UPDATE disciplina SET ementa = 'Criação de APIs RESTful com Node.js e Express. Autenticação com JWT. Integração com banco de dados via ORM (Sequelize/Prisma). Tratamento de erros e validação de dados. Testes de API com Postman e Jest. Deploy em provedores cloud: Railway, Render e AWS. Introdução a microserviços.' WHERE codigo = 'WEB002';

UPDATE disciplina SET ementa = 'Listas encadeadas simples e duplas. Pilhas e filas. Árvores binárias de busca e AVL. Tabelas hash. Grafos: representações e algoritmos (BFS, DFS, Dijkstra). Complexidade de algoritmos (notação Big-O). Algoritmos de ordenação e busca. Implementações práticas em Java ou Python.' WHERE codigo = 'ED001';

UPDATE disciplina SET ementa = 'Bancos de dados NoSQL: conceitos, categorias e casos de uso. MongoDB na prática: CRUD, aggregation pipeline, índices. Redis como cache e message broker. Transações e controle de concorrência em bancos relacionais. Query optimization e explain plans. Replicação e particionamento (sharding).' WHERE codigo = 'BD002';

UPDATE disciplina SET ementa = 'Conceitos de gerenciamento de projetos de software. PMBOK e metodologias ágeis. Planejamento: escopo, tempo, custo e riscos. Ferramentas: Jira, Trello e GitHub Projects. Estimativas de esforço (Planning Poker, Story Points). Monitoramento e controle de projetos. Gestão de equipes e comunicação.' WHERE codigo = 'GP001';

UPDATE disciplina SET ementa = 'Conceitos de segurança da informação: confidencialidade, integridade e disponibilidade. Criptografia simétrica e assimétrica. HTTPS e certificados TLS/SSL. Autenticação multifator e OAuth 2.0. OWASP Top 10: principais vulnerabilidades web. Firewall, IDS e IPS. LGPD e privacidade de dados. Pentest introdutório.' WHERE codigo = 'SEG001';

-- -------------------------------------------------------
-- POSTS — atualizar com conteúdo mais rico e profissional
-- -------------------------------------------------------

UPDATE post SET
  titulo    = 'Inovatech promove 5ª Feira de Inovação e Tecnologia',
  resumo    = 'Com mais de 200 projetos apresentados por alunos dos três cursos, a 5ª edição da Feira de Inovação reuniu empresas parceiras, investidores e a comunidade acadêmica em um evento memorável.',
  conteudo_md = E'# 5ª Feira de Inovação e Tecnologia da Inovatech\n\nA Faculdade Inovatech realizou no último mês a sua **5ª edição da Feira de Inovação e Tecnologia**, um dos maiores eventos do segmento no interior do estado.\n\n## Números da Edição\n\n| Indicador | Resultado |\n|-----------|----------|\n| Projetos apresentados | 212 |\n| Alunos participantes | 480 |\n| Empresas parceiras | 28 |\n| Visitantes externos | 1.200+ |\n\n## Projetos Destaques\n\n### 🥇 1º Lugar — Sistema de Monitoramento Agrícola com IoT\nEquipe do 5º semestre de TADS desenvolveu sensores de baixo custo integrados a uma plataforma web em tempo real para auxiliar agricultores familiares.\n\n### 🥈 2º Lugar — Plataforma de Ensino Personalizado com IA\nAlunos de Sistemas para Internet criaram um sistema que adapta o conteúdo de estudo ao ritmo e desempenho de cada aluno, usando algoritmos de machine learning.\n\n### 🥉 3º Lugar — ERP Simplificado para Pequenas Empresas\nProjeto de Gestão Empresarial entregou um sistema completo de gestão financeira e estoque para MEIs e microempresas, com foco em acessibilidade.\n\n## Palavras do Diretor\n\n> *"Cada projeto apresentado aqui é prova de que o ensino de qualidade transforma vidas e cria soluções reais para problemas reais. Estamos muito orgulhosos de toda a comunidade Inovatech."*\n> — Prof. Dr. Alexandre Mendes, Diretor Acadêmico\n\n## Próxima Edição\n\nA **6ª Feira de Inovação** está confirmada para **outubro de 2026**. As inscrições de projetos abrem em agosto. Fique ligado no portal!',
  tags      = ARRAY['eventos', 'inovação', 'tecnologia', 'destaque', 'feira']
WHERE slug = 'inovatech-promove-feira-de-inovacao-e-tecnologia-2026';

UPDATE post SET
  titulo    = 'Dois novos laboratórios equipados com tecnologia de ponta são inaugurados',
  resumo    = 'Investimento de R$ 380 mil em equipamentos modernos vai beneficiar mais de 800 alunos dos cursos de tecnologia com workstations de alta performance e internet de 1Gbps.',
  conteudo_md = E'# Novos Laboratórios: um salto na infraestrutura da Inovatech\n\nA Faculdade Inovatech concluiu um dos maiores investimentos em infraestrutura de sua história: **dois novos laboratórios de informática** totalmente equipados, disponíveis a partir desta semana.\n\n## Especificações dos Equipamentos\n\nCada laboratório conta com **40 workstations** de alto desempenho:\n\n- **CPU:** Intel Core i9 de 13ª geração\n- **RAM:** 32 GB DDR5\n- **Armazenamento:** SSD NVMe 1 TB\n- **Placa de vídeo:** NVIDIA RTX 3060 (para disciplinas de IA e computação gráfica)\n- **Monitor:** Dual LG 24" Full HD\n- **Conectividade:** Internet fibra óptica 1Gbps, Wi-Fi 6\n\n## Softwares Pré-instalados\n\n**Desenvolvimento:**\n- VS Code, IntelliJ IDEA, PyCharm, Android Studio\n- Docker Desktop, Postman, DBeaver\n\n**Data Science:**\n- Anaconda, Jupyter Lab, R Studio\n\n**Design e UX:**\n- Figma (web), Adobe XD, Inkscape\n\n## Horário de Funcionamento\n\nOs laboratórios estarão disponíveis para uso livre pelos alunos:\n- **Segunda a sexta:** 7h às 22h30\n- **Sábado:** 8h às 17h\n\nReservas para projetos e trabalhos em grupo podem ser feitas pelo portal acadêmico com até 7 dias de antecedência.\n\n## Depoimento\n\n> *"Trabalhar com esses equipamentos é outro nível. Agora consigo rodar modelos de machine learning sem travar!"*\n> — Maria Oliveira, 3º semestre de TADS',
  tags      = ARRAY['infraestrutura', 'laboratório', 'tecnologia']
WHERE slug = 'novos-laboratorios-de-informatica-inaugurados';

UPDATE post SET
  titulo    = 'Equipe da Inovatech vence Hackathon Regional com solução para saúde pública',
  resumo    = 'Em 48 horas de desenvolvimento intenso, o time CodeStorm criou um sistema de triagem inteligente para UBSs que reduziu em 40% o tempo de espera nos testes realizados. Conheça o projeto e seus criadores.',
  conteudo_md = E'# CodeStorm: campeões do Hackathon Regional de Tecnologia 2026\n\nOs alunos João Silva, Maria Oliveira e Lucas Martins, do curso de **Análise e Desenvolvimento de Sistemas**, representaram a Inovatech no Hackathon Regional de Tecnologia e saíram campeões!\n\n## O Desafio\n\nO tema do hackathon era **"Tecnologia para a Saúde Pública"**. Participaram 42 equipes de 18 instituições de ensino do estado.\n\n## A Solução: TríagemSmart\n\nO time desenvolveu o **TríagemSmart**, uma plataforma de triagem inteligente para Unidades Básicas de Saúde (UBSs) composta por:\n\n### 📱 Aplicativo Mobile (React Native)\n- Agendamento de consultas online\n- Check-in antecipado com QR Code\n- Acompanhamento em tempo real da fila\n- Histórico de atendimentos\n\n### 🧠 Engine de Priorização (Python + ML)\n- Análise de sintomas relatados pelo paciente\n- Algoritmo de classificação de risco baseado no Protocolo de Manchester\n- Integração com prontuário eletrônico\n\n### 📊 Dashboard para Gestores (React + Recharts)\n- Painel em tempo real com métricas de atendimento\n- Alertas de sobrecarga e gargalos\n- Relatórios exportáveis para o Ministério da Saúde\n\n## Resultados Obtidos no Piloto\n\n| Métrica | Antes | Depois | Melhoria |\n|---------|-------|--------|----------|\n| Tempo médio de espera | 2h40 | 1h35 | **-40%** |\n| Casos críticos não identificados | 12% | 1.8% | **-85%** |\n| Satisfação dos pacientes | 3.1/5 | 4.6/5 | **+48%** |\n\n## Premiação\n\n- 🏆 R$ 5.000,00 em dinheiro\n- Convite para apresentação no *TechSummit SP 2026*\n- Mentoria de 6 meses com a aceleradora InovaBrasil\n- Carta de recomendação da Secretaria Estadual de Saúde\n\n## O que os alunos dizem\n\n> *"Nunca imaginei que em 48 horas conseguiríamos construir algo que realmente funciona. A Inovatech nos preparou muito bem."*\n> — João Silva\n\n> *"Foi exaustivo, mas valeu cada minuto. Esse projeto vai continuar — queremos implantá-lo de verdade."*\n> — Maria Oliveira',
  tags      = ARRAY['destaque', 'TADS', 'hackathon', 'premiação', 'saúde']
WHERE slug = 'alunos-tads-vencem-hackathon-regional-2026';

UPDATE post SET
  titulo    = 'Matrículas 2026.2: tudo que você precisa saber',
  resumo    = 'As matrículas para o segundo semestre de 2026 abrem no dia 1º de julho. Confira o calendário completo, as disciplinas disponíveis, as regras de trancamento e como se matricular pelo portal acadêmico.',
  conteudo_md = E'# Matrículas 2026.2 — Guia Completo\n\nO segundo semestre de 2026 está chegando! Confira **tudo que você precisa saber** para fazer sua matrícula sem erros.\n\n## 📅 Calendário\n\n| Evento | Data |\n|--------|------|\n| Abertura das matrículas | **01/07/2026** |\n| Prazo para alunos veteranos | 08/07/2026 |\n| Prazo para calouros | 15/07/2026 |\n| Início das aulas | **28/07/2026** |\n| Trancamento sem ônus financeiro | até 15/08/2026 |\n| Trancamento com ônus de 50% | até 31/08/2026 |\n| Provas P1 | 22/09 a 26/09/2026 |\n| Provas P2 | 01/12 a 05/12/2026 |\n| Encerramento do semestre | 19/12/2026 |\n\n## 📋 Passo a Passo da Matrícula\n\n1. Acesse o **Portal Acadêmico** em `portal.inovatech.edu`\n2. Faça login com seu e-mail e senha\n3. Clique em **"Matrícula"** no menu lateral esquerdo\n4. Selecione o semestre **2026.2**\n5. Escolha as disciplinas disponíveis para o seu semestre\n6. Verifique se há pré-requisitos pendentes\n7. Confirme e aguarde o e-mail de confirmação\n\n## ⚠️ Regras Importantes\n\n- Alunos com **pendências financeiras** não poderão se matricular\n- A **carga horária máxima** é de 400h por semestre\n- Disciplinas com pré-requisito reprovado devem ser cursadas primeiro\n- O trancamento de matrícula preserva o vínculo institucional por até 2 semestres consecutivos\n\n## 🆘 Dúvidas?\n\nEntre em contato com a Secretaria Acadêmica:\n- 📧 secretaria@inovatech.edu\n- 📞 (17) 3322-4400\n- 🕐 Atendimento: seg a sex, 8h às 20h',
  tags      = ARRAY['matrícula', 'calendário', 'avisos', '2026.2']
WHERE slug = 'periodo-matriculas-2026-2';

UPDATE post SET
  titulo    = 'Semana de Palestras 2026: grandes nomes do mercado no campus Inovatech',
  resumo    = 'Durante toda a primeira semana de junho, a Inovatech recebe executivos e especialistas do Google, Nubank, Embrapa e outras empresas líderes para palestras gratuitas abertas ao público.',
  conteudo_md = E'# Semana de Palestras Inovatech 2026\n\nA maior semana de conhecimento do ano chegou! A **Semana de Palestras Inovatech 2026** reunirá profissionais de referência para compartilhar experiências, tendências e oportunidades do mercado.\n\n## 📅 Programação Completa\n\n### Segunda-feira, 01/06 — Auditório Principal | 19h00\n**"Carreira em Cloud Computing e DevOps"**\n*Engenheiro Rafael Torres — Google Cloud Brazil*\n\nNa palestra, Rafael compartilha como é trabalhar no maior provedor de cloud do mundo, as habilidades mais valorizadas em 2026 e dicas práticas para conquistar certificações AWS, Azure e GCP.\n\n---\n\n### Terça-feira, 02/06 — Auditório Principal | 19h30\n**"Fintechs, Open Banking e o Futuro do Dinheiro"**\n*Dra. Camila Reis — Head de Engenharia no Nubank*\n\nComo o Nubank processa 1 bilhão de transações por mês com alta disponibilidade? Camila fala sobre arquitetura de microserviços, Clojure, Kafka e a cultura de engenharia que fez do Nubank um unicórnio global.\n\n---\n\n### Quarta-feira, 03/06 — Lab de Inovação | 14h00\n**Workshop: "Prototipação Rápida com Figma e No-Code"**\n*Designer Renata Costa — Fundadora da StartupUI*\n*(Vagas limitadas a 30 participantes — inscrição prévia obrigatória)*\n\n---\n\n### Quinta-feira, 04/06 — Auditório Principal | 19h00\n**"Tecnologia no Agronegócio: da IoT ao Satélite"**\n*Dr. Marcos Alves — Pesquisador Sênior, Embrapa Informática Agropecuária*\n\nComo o Brasil, o maior exportador agrícola do mundo, usa drones, IoT, IA e imagens de satélite para aumentar a produtividade e reduzir o impacto ambiental da agricultura.\n\n---\n\n### Sexta-feira, 05/06 — Auditório Principal | 19h00\n**Painel: "Mercado de Tecnologia em 2026 — Onde estão as vagas?"**\n*Participantes: Rafael Torres (Google), Dra. Camila Reis (Nubank), Dr. Marcos Alves (Embrapa) + Mediação da Coordenação Inovatech*\n\n## 🎟️ Inscrições\n\nAs palestras são **gratuitas** e abertas à comunidade. Inscreva-se pelo portal: `eventos.inovatech.edu`\n\n**Certificado de participação** disponível para quem comparecer a pelo menos 3 eventos.\n\n> Vagas limitadas! As inscrições encerram 24h antes de cada palestra.',
  tags      = ARRAY['palestras', 'eventos', 'mercado', 'carreira', 'google', 'nubank']
WHERE slug = 'semana-palestras-profissionais-mercado-2026';

UPDATE post SET
  titulo    = '"Inovatech na Escola": extensão universitária transforma vidas na rede pública',
  resumo    = 'Mais de 320 estudantes do ensino médio de 5 escolas públicas tiveram seu primeiro contato com programação e tecnologia graças ao projeto de extensão conduzido por professores e alunos voluntários da Inovatech.',
  conteudo_md = E'# Inovatech na Escola: tecnologia que transforma\n\nO projeto de extensão universitária **"Inovatech na Escola"** encerrou sua segunda edição com resultados expressivos e emotivos. Por 3 meses, professores e alunos voluntários da Faculdade Inovatech visitaram 5 escolas públicas municipais e estaduais de Jales e região, levando conhecimento tecnológico a quem mais precisa.\n\n## 🎯 Objetivos do Projeto\n\n- Promover a **inclusão digital** e o pensamento computacional no ensino básico\n- Despertar o interesse de jovens de baixa renda pelas carreiras em tecnologia\n- Fortalecer o vínculo entre a Inovatech e a comunidade\n- Proporcionar experiência prática de docência aos alunos voluntários\n\n## 📊 Resultados 2026\n\n| Indicador | Resultado |\n|-----------|----------|\n| Escolas atendidas | 5 |\n| Alunos beneficiados | 324 |\n| Aulas ministradas | 48 |\n| Alunos Inovatech voluntários | 18 |\n| Professores coordenadores | 3 |\n| % de alunos interessados em fazer faculdade de TI (pós-projeto) | 67% |\n\n## 📚 Conteúdo das Oficinas\n\n**Módulo 1 — Pensamento Computacional (4h)**\nJogos de lógica, resolução de problemas e raciocínio algorítmico sem computador.\n\n**Módulo 2 — Scratch para Iniciantes (6h)**\nProgramação visual com criação de animações, jogos simples e histórias interativas.\n\n**Módulo 3 — Introdução ao Python (8h)**\nVariáveis, condições, laços e criação de um mini-jogo textual.\n\n**Módulo 4 — O que é a Internet? (4h)**\nComo funciona a web, o que fazem desenvolvedores, designers e analistas.\n\n## 💬 Depoimentos\n\n> *"Nunca pensei que fosse conseguir fazer um jogo. Agora quero fazer computação!"*\n> — Aluno do 9º ano, E.E. Dr. João Pessoa\n\n> *"Ensinar me fez aprender de um jeito diferente. Fui eu quem mais aprendi."*\n> — Lucas Martins, voluntário, 3º semestre de TADS\n\n## 📌 Próxima Edição\n\nAs inscrições para a **3ª edição** do projeto (agosto–novembro/2026) abrem em julho pelo portal acadêmico. Alunos de qualquer semestre e curso podem participar.',
  tags      = ARRAY['extensão', 'comunidade', 'inclusão digital', 'voluntariado']
WHERE slug = 'projeto-extensao-tecnologia-escolas-publicas';
